remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: PyApiTester
description: A lightweight CLI backend API testing tool
show_downloads: false

site.url: "https://sl-alex.net/pyapitester"